/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.mov

import java.time.LocalDate
import java.time.Month

fun main() {
    var pessoa: Pessoa = Pessoa("Henrique", LocalDate.of(2004, Month.SEPTEMBER, 20))
    pessoa.nome = "Teste"

    var pessoa2: Pessoa = Pessoa()

    println(pessoa)
    println(pessoa2)



    var carro: Carro = Carro()

    carro.velocidade = -1

    println(carro)


    val cachorro = Cachorro("Totó")
    println(cachorro.fazerSom())
    cachorro.dormir()
}
