/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.mov

import kotlinx.coroutines.*

//USANDO
//fun main() = runBlocking{
//    launch{
//        delay(1000L)
//        println("Terminei tarefa demorada")
//    }
//    println("Fim programa")
//}

suspend fun tarefaDemorada(){
    delay(2000L)
    println("Tarefa concluída")
}

fun main() = runBlocking{
    println("Iniciando...")
    tarefaDemorada()
    println("Fim programa")
}