/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.mov

fun main() {
    //É uma conveção manter o padrão de kwargs na nomenclatura dos argumentos
    println(olaMundo(nome = "Henrique", saudacao = "Bem-vindo,"))

    //É possivel identificar o tipo da variavel que vá ser um retorno de função, no exemplo abaixo do aux é possivel que diga a variavel que ela possa receber funcoes com retorno de string e argumentos (String, Int)
    val aux: (String, Int) -> String





}

//É possível ter um default por parametro igual no python
fun olaMundo(nome: String= "Juca", saudacao: String= "Olá,"): String {
    return "$nome $saudacao"
}

