/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.mov

fun main() {
    println("Olá mundo")

    // Declaração de variáveis com tipo explícito
    var nome: String // tipo String, mutável
    nome = "João" // atribuição de valor
    // Declaração de variáveis com tipo explícito e inicialização
    var idade: Int = 30 // tipo Int, mutável e inicializado com 30
    // Declaração de variáveis com tipo inferido
    val valor = 25.0 // tipo inferido como Int, imutável
    var ativo = true // tipo inferido como Boolean, mutável
    idade = 20 // atribuição de novo valor
    // valor = 3.0 // erro: não é possível atribuir valor a uma variável imutável

    val disciplina: String = "MOV";

    //exercEscreverNomeIdade()
    execNumeroAleatorio()
}


fun exercEscreverNomeIdade(){
    print("Entre com seu nome: ")
    val nome: String = readlnOrNull() ?: "Não Informado"
    print("Entre com sua idade: ")
    val idade: Int = readlnOrNull()?.toIntOrNull() ?: 0

    println("Seu nome é: $nome, sua idade é: $idade")
    //println("Seu nome é: $nome, sua idade é: $idade")
}

fun execNumeroAleatorio(){
    val sorteado: Int = (1..10).random()
    var tentativa: Int = 0
    println("Valor sorteado $sorteado")
    do{
        print("Tentativa: $tentativa: ")
        val valorDigitado: Int? = readlnOrNull()?.toInt()
        tentativa++
    }while(valorDigitado != sorteado)
    println("Show, acertou")
}
